/**
 * link.ts -- Telegram-to-Web account claim flow.
 *
 * Handles the /link <token> command. The token is a 32-byte random hex string
 * generated by the Web app. The Web app computes:
 *   token_hash = HMAC-SHA256(LINK_TOKEN_SECRET, rawToken)
 * and inserts a link_tokens row with (token_hash, web_user_id, expires_at).
 *
 * This module:
 *   1. Recomputes the same hash from the received raw token.
 *   2. Atomically DELETEs the link_tokens row (prevents double-use).
 *   3. Merges the Telegram channel_identities row to the web_user_id.
 *
 * Atomicity guarantee:
 *   DELETE + RETURNING in a single query is atomic. If two /link commands race
 *   with the same token, only one will get a RETURNING row. The other gets an
 *   error reply without touching channel_identities.
 */

import { createServerClient } from '@clawos/shared'
import { hmacSha256 } from '@clawos/security'
import { ENV } from './env.js'

export type LinkResult =
  | { ok: true }
  | { ok: false; reason: 'invalid_or_expired' | 'already_linked' | 'internal_error' }

/**
 * Validate a /link token and merge the Telegram user to the web user.
 *
 * @param telegramUserId  Telegram numeric user ID as a string.
 * @param rawToken        The raw token from the /link command.
 * @returns               LinkResult indicating success or failure reason.
 */
export async function claimLinkToken(
  telegramUserId: string,
  rawToken: string,
): Promise<LinkResult> {
  const supabase = createServerClient()

  // 1. Recompute the hash the Web app stored.
  const tokenHash = hmacSha256(ENV.LINK_TOKEN_SECRET, rawToken)

  // 2. Atomic DELETE + RETURNING -- prevents double-use.
  //    If expired or invalid, no row is returned.
  const { data: tokenRows, error: deleteError } = await supabase
    .from('link_tokens')
    .delete()
    .eq('token_hash', tokenHash)
    .gt('expires_at', new Date().toISOString())
    .select('web_user_id')

  if (deleteError) {
    console.error('[link] link_tokens delete error:', deleteError.message)
    return { ok: false, reason: 'internal_error' }
  }

  const tokenRow = tokenRows?.[0]
  if (!tokenRow) {
    // Token not found or expired (also covers already-used tokens since the row was deleted).
    return { ok: false, reason: 'invalid_or_expired' }
  }

  const webUserId = tokenRow.web_user_id

  // 3. Check if this Telegram user already has a channel_identity.
  const { data: existing } = await supabase
    .from('channel_identities')
    .select('user_id')
    .eq('channel', 'telegram')
    .eq('channel_user_id', telegramUserId)
    .maybeSingle()

  if (existing) {
    if (existing.user_id === webUserId) {
      // Already linked to the same account -- idempotent success.
      return { ok: true }
    }
    // Linked to a different account -- cannot merge here.
    return { ok: false, reason: 'already_linked' }
  }

  // 4. Merge: update or insert the channel_identities row to point to webUserId.
  //    The Telegram user may have a provisional identity from a first-message creation
  //    (tg_<id>@clawos.internal). We update that row to point to the web user.
  const { error: upsertError } = await supabase
    .from('channel_identities')
    .upsert(
      { user_id: webUserId, channel: 'telegram', channel_user_id: telegramUserId },
      { onConflict: 'channel,channel_user_id' },
    )

  if (upsertError) {
    console.error('[link] channel_identities upsert error:', upsertError.message)
    return { ok: false, reason: 'internal_error' }
  }

  return { ok: true }
}
